const workingcountries = [
	{ id: '1', country_code: 'AF', value: 'Afghanistan' },
	{ id: '2', country_code: 'AL', value: 'Albania' },
	{ id: '3', country_code: 'DZ', value: 'Algeria' },
	{ id: '4', country_code: 'DS', value: 'American Samoa' },
	{ id: '5', country_code: 'AD', value: 'Andorra' },
	{ id: '6', country_code: 'AO', value: 'Angola' },
	{ id: '7', country_code: 'AI', value: 'Anguilla' },
	{ id: '8', country_code: 'AQ', value: 'Antarctica' },
	{ id: '9', country_code: 'AG', value: 'Antigua and Barbuda' },
	{ id: '10', country_code: 'AR', value: 'Argentina' },
	{ id: '11', country_code: 'AM', value: 'Armenia' },
	{ id: '12', country_code: 'AW', value: 'Aruba' },
	{ id: '13', country_code: 'AU', value: 'Australia' },
	{ id: '14', country_code: 'AT', value: 'Austria' },
	{ id: '15', country_code: 'AZ', value: 'Azerbaijan' },
	{ id: '16', country_code: 'BS', value: 'Bahamas' },
	{ id: '17', country_code: 'BH', value: 'Bahrain' },
	{ id: '18', country_code: 'BD', value: 'Bangladesh' },
	{ id: '19', country_code: 'BB', value: 'Barbados' },
	{ id: '20', country_code: 'BY', value: 'Belarus' },
	{ id: '21', country_code: 'BE', value: 'Belgium' },
	{ id: '22', country_code: 'BZ', value: 'Belize' },
	{ id: '23', country_code: 'BJ', value: 'Benin' },
	{ id: '24', country_code: 'BM', value: 'Bermuda' },
	{ id: '25', country_code: 'BT', value: 'Bhutan' },
	{ id: '26', country_code: 'BO', value: 'Bolivia' },
	{ id: '27', country_code: 'BA', value: 'Bosnia and Herzegovina' },
	{ id: '28', country_code: 'BW', value: 'Botswana' },
	{ id: '29', country_code: 'BV', value: 'Bouvet Island' },
	{ id: '30', country_code: 'BR', value: 'Brazil' },
	{ id: '31', country_code: 'IO', value: 'British Indian Ocean Territory' },
	{ id: '32', country_code: 'BN', value: 'Brunei Darussalam' },
	{ id: '33', country_code: 'BG', value: 'Bulgaria' },
	{ id: '34', country_code: 'BF', value: 'Burkina Faso' },
	{ id: '35', country_code: 'BI', value: 'Burundi' },
	{ id: '36', country_code: 'KH', value: 'Cambodia' },
	{ id: '37', country_code: 'CM', value: 'Cameroon' },
	{ id: '38', country_code: 'CA', value: 'Canada' },
	{ id: '39', country_code: 'CV', value: 'Cape Verde' },
	{ id: '40', country_code: 'KY', value: 'Cayman Islands' },
	{ id: '41', country_code: 'CF', value: 'Central African Republic' },
	{ id: '42', country_code: 'TD', value: 'Chad' },
	{ id: '43', country_code: 'CL', value: 'Chile' },
	{ id: '44', country_code: 'CN', value: 'China' },
	{ id: '45', country_code: 'CX', value: 'Christmas Island' },
	{ id: '46', country_code: 'CC', value: 'Cocos (Keeling) Islands' },
	{ id: '47', country_code: 'CO', value: 'Colombia' },
	{ id: '48', country_code: 'KM', value: 'Comoros' },
	{ id: '49', country_code: 'CG', value: 'Congo' },
	{ id: '50', country_code: 'CK', value: 'Cook Islands' },
	{ id: '51', country_code: 'CR', value: 'Costa Rica' },
	{ id: '52', country_code: 'HR', value: 'Croatia (Hrvatska)' },
	{ id: '53', country_code: 'CU', value: 'Cuba' },
	{ id: '54', country_code: 'CY', value: 'Cyprus' },
	{ id: '55', country_code: 'CZ', value: 'Czech Republic' },
	{ id: '56', country_code: 'DK', value: 'Denmark' },
	{ id: '57', country_code: 'DJ', value: 'Djibouti' },
	{ id: '58', country_code: 'DM', value: 'Dominica' },
	{ id: '59', country_code: 'DO', value: 'Dominican Republic' },
	{ id: '60', country_code: 'TP', value: 'East Timor' },
	{ id: '61', country_code: 'EC', value: 'Ecuador' },
	{ id: '62', country_code: 'EG', value: 'Egypt' },
	{ id: '63', country_code: 'SV', value: 'El Salvador' },
	{ id: '64', country_code: 'GQ', value: 'Equatorial Guinea' },
	{ id: '65', country_code: 'ER', value: 'Eritrea' },
	{ id: '66', country_code: 'EE', value: 'Estonia' },
	{ id: '67', country_code: 'ET', value: 'Ethiopia' },
	{ id: '68', country_code: 'FK', value: 'Falkland Islands (Malvinas)' },
	{ id: '69', country_code: 'FO', value: 'Faroe Islands' },
	{ id: '70', country_code: 'FJ', value: 'Fiji' },
	{ id: '71', country_code: 'FI', value: 'Finland' },
	{ id: '72', country_code: 'FR', value: 'France' },
	{ id: '73', country_code: 'FX', value: 'France, Metropolitan' },
	{ id: '74', country_code: 'GF', value: 'French Guiana' },
	{ id: '75', country_code: 'PF', value: 'French Polynesia' },
	{ id: '76', country_code: 'TF', value: 'French Southern Territories' },
	{ id: '77', country_code: 'GA', value: 'Gabon' },
	{ id: '78', country_code: 'GM', value: 'Gambia' },
	{ id: '79', country_code: 'GE', value: 'Georgia' },
	{ id: '80', country_code: 'DE', value: 'Germany' },
	{ id: '81', country_code: 'GH', value: 'Ghana' },
	{ id: '82', country_code: 'GI', value: 'Gibraltar' },
	{ id: '83', country_code: 'GK', value: 'Guernsey' },
	{ id: '84', country_code: 'GR', value: 'Greece' },
	{ id: '85', country_code: 'GL', value: 'Greenland' },
	{ id: '86', country_code: 'GD', value: 'Grenada' },
	{ id: '87', country_code: 'GP', value: 'Guadeloupe' },
	{ id: '88', country_code: 'GU', value: 'Guam' },
	{ id: '89', country_code: 'GT', value: 'Guatemala' },
	{ id: '90', country_code: 'GN', value: 'Guinea' },
	{ id: '91', country_code: 'GW', value: 'Guinea-Bissau' },
	{ id: '92', country_code: 'GY', value: 'Guyana' },
	{ id: '93', country_code: 'HT', value: 'Haiti' },
	{ id: '94', country_code: 'HM', value: 'Heard and Mc Donald Islands' },
	{ id: '95', country_code: 'HN', value: 'Honduras' },
	{ id: '96', country_code: 'HK', value: 'Hong Kong' },
	{ id: '97', country_code: 'HU', value: 'Hungary' },
	{ id: '98', country_code: 'IS', value: 'Iceland' },
	{ id: '99', country_code: 'IN', value: 'India' },
	{ id: '100', country_code: 'IM', value: 'Isle of Man' },
	{ id: '101', country_code: 'ID', value: 'Indonesia' },
	{ id: '102', country_code: 'IR', value: 'Iran (Islamic Republic of)' },
	{ id: '103', country_code: 'IQ', value: 'Iraq' },
	{ id: '104', country_code: 'IE', value: 'Ireland' },
	{ id: '105', country_code: 'IL', value: 'Israel' },
	{ id: '106', country_code: 'IT', value: 'Italy' },
	{ id: '107', country_code: 'CI', value: 'Ivory Coast' },
	{ id: '108', country_code: 'JE', value: 'Jersey' },
	{ id: '109', country_code: 'JM', value: 'Jamaica' },
	{ id: '110', country_code: 'JP', value: 'Japan' },
	{ id: '111', country_code: 'JO', value: 'Jordan' },
	{ id: '112', country_code: 'KZ', value: 'Kazakhstan' },
	{ id: '113', country_code: 'KE', value: 'Kenya' },
	{ id: '114', country_code: 'KI', value: 'Kiribati' },
	{ id: '115', country_code: 'KP', value: "Korea, Democratic People's Republic of" },
	{ id: '116', country_code: 'KR', value: 'Korea, Republic of' },
	{ id: '117', country_code: 'XK', value: 'Kosovo' },
	{ id: '118', country_code: 'KW', value: 'Kuwait' },
	{ id: '119', country_code: 'KG', value: 'Kyrgyzstan' },
	{ id: '120', country_code: 'LA', value: "Lao People's Democratic Republic" },
	{ id: '121', country_code: 'LV', value: 'Latvia' },
	{ id: '122', country_code: 'LB', value: 'Lebanon' },
	{ id: '123', country_code: 'LS', value: 'Lesotho' },
	{ id: '124', country_code: 'LR', value: 'Liberia' },
	{ id: '125', country_code: 'LY', value: 'Libyan Arab Jamahiriya' },
	{ id: '126', country_code: 'LI', value: 'Liechtenstein' },
	{ id: '127', country_code: 'LT', value: 'Lithuania' },
	{ id: '128', country_code: 'LU', value: 'Luxembourg' },
	{ id: '129', country_code: 'MO', value: 'Macau' },
	{ id: '130', country_code: 'MK', value: 'Macedonia' },
	{ id: '131', country_code: 'MG', value: 'Madagascar' },
	{ id: '132', country_code: 'MW', value: 'Malawi' },
	{ id: '133', country_code: 'MY', value: 'Malaysia' },
	{ id: '134', country_code: 'MV', value: 'Maldives' },
	{ id: '135', country_code: 'ML', value: 'Mali' },
	{ id: '136', country_code: 'MT', value: 'Malta' },
	{ id: '137', country_code: 'MH', value: 'Marshall Islands' },
	{ id: '138', country_code: 'MQ', value: 'Martinique' },
	{ id: '139', country_code: 'MR', value: 'Mauritania' },
	{ id: '140', country_code: 'MU', value: 'Mauritius' },
	{ id: '141', country_code: 'TY', value: 'Mayotte' },
	{ id: '142', country_code: 'MX', value: 'Mexico' },
	{ id: '143', country_code: 'FM', value: 'Micronesia, Federated States of' },
	{ id: '144', country_code: 'MD', value: 'Moldova, Republic of' },
	{ id: '145', country_code: 'MC', value: 'Monaco' },
	{ id: '146', country_code: 'MN', value: 'Mongolia' },
	{ id: '147', country_code: 'ME', value: 'Montenegro' },
	{ id: '148', country_code: 'MS', value: 'Montserrat' },
	{ id: '149', country_code: 'MA', value: 'Morocco' },
	{ id: '150', country_code: 'MZ', value: 'Mozambique' },
	{ id: '151', country_code: 'MM', value: 'Myanmar' },
	{ id: '152', country_code: 'NA', value: 'Namibia' },
	{ id: '153', country_code: 'NR', value: 'Nauru' },
	{ id: '154', country_code: 'NP', value: 'Nepal' },
	{ id: '155', country_code: 'NL', value: 'Netherlands' },
	{ id: '156', country_code: 'AN', value: 'Netherlands Antilles' },
	{ id: '157', country_code: 'NC', value: 'New Caledonia' },
	{ id: '158', country_code: 'NZ', value: 'New Zealand' },
	{ id: '159', country_code: 'NI', value: 'Nicaragua' },
	{ id: '160', country_code: 'NE', value: 'Niger' },
	{ id: '161', country_code: 'NG', value: 'Nigeria' },
	{ id: '162', country_code: 'NU', value: 'Niue' },
	{ id: '163', country_code: 'NF', value: 'Norfolk Island' },
	{ id: '164', country_code: 'MP', value: 'Northern Mariana Islands' },
	{ id: '165', country_code: 'NO', value: 'Norway' },
	{ id: '166', country_code: 'OM', value: 'Oman' },
	{ id: '167', country_code: 'PK', value: 'Pakistan' },
	{ id: '168', country_code: 'PW', value: 'Palau' },
	{ id: '169', country_code: 'PS', value: 'Palestine' },
	{ id: '170', country_code: 'PA', value: 'Panama' },
	{ id: '171', country_code: 'PG', value: 'Papua New Guinea' },
	{ id: '172', country_code: 'PY', value: 'Paraguay' },
	{ id: '173', country_code: 'PE', value: 'Peru' },
	{ id: '174', country_code: 'PH', value: 'Philippines' },
	{ id: '175', country_code: 'PN', value: 'Pitcairn' },
	{ id: '176', country_code: 'PL', value: 'Poland' },
	{ id: '177', country_code: 'PT', value: 'Portugal' },
	{ id: '178', country_code: 'PR', value: 'Puerto Rico' },
	{ id: '179', country_code: 'QA', value: 'Qatar' },
	{ id: '180', country_code: 'RE', value: 'Reunion' },
	{ id: '181', country_code: 'RO', value: 'Romania' },
	{ id: '182', country_code: 'RU', value: 'Russian Federation' },
	{ id: '183', country_code: 'RW', value: 'Rwanda' },
	{ id: '184', country_code: 'KN', value: 'Saint Kitts and Nevis' },
	{ id: '185', country_code: 'LC', value: 'Saint Lucia' },
	{ id: '186', country_code: 'VC', value: 'Saint Vincent and the Grenadines' },
	{ id: '187', country_code: 'WS', value: 'Samoa' },
	{ id: '188', country_code: 'SM', value: 'San Marino' },
	{ id: '189', country_code: 'ST', value: 'Sao Tome and Principe' },
	{ id: '190', country_code: 'SA', value: 'Saudi Arabia' },
	{ id: '191', country_code: 'SN', value: 'Senegal' },
	{ id: '192', country_code: 'RS', value: 'Serbia' },
	{ id: '193', country_code: 'SC', value: 'Seychelles' },
	{ id: '194', country_code: 'SL', value: 'Sierra Leone' },
	{ id: '195', country_code: 'SG', value: 'Singapore' },
	{ id: '196', country_code: 'SK', value: 'Slovakia' },
	{ id: '197', country_code: 'SI', value: 'Slovenia' },
	{ id: '198', country_code: 'SB', value: 'Solomon Islands' },
	{ id: '199', country_code: 'SO', value: 'Somalia' },
	{ id: '200', country_code: 'ZA', value: 'South Africa' },
	{ id: '201', country_code: 'GS', value: 'South Georgia South Sandwich Islands' },
	{ id: '202', country_code: 'SS', value: 'South Sudan' },
	{ id: '203', country_code: 'ES', value: 'Spain' },
	{ id: '204', country_code: 'LK', value: 'Sri Lanka' },
	{ id: '205', country_code: 'SH', value: 'St. Helena' },
	{ id: '206', country_code: 'PM', value: 'St. Pierre and Miquelon' },
	{ id: '207', country_code: 'SD', value: 'Sudan' },
	{ id: '208', country_code: 'SR', value: 'Suriname' },
	{ id: '209', country_code: 'SJ', value: 'Svalbard and Jan Mayen Islands' },
	{ id: '210', country_code: 'SZ', value: 'Swaziland' },
	{ id: '211', country_code: 'SE', value: 'Sweden' },
	{ id: '212', country_code: 'CH', value: 'Switzerland' },
	{ id: '213', country_code: 'SY', value: 'Syrian Arab Republic' },
	{ id: '214', country_code: 'TW', value: 'Taiwan' },
	{ id: '215', country_code: 'TJ', value: 'Tajikistan' },
	{ id: '216', country_code: 'TZ', value: 'Tanzania, United Republic of' },
	{ id: '217', country_code: 'TH', value: 'Thailand' },
	{ id: '218', country_code: 'TG', value: 'Togo' },
	{ id: '219', country_code: 'TK', value: 'Tokelau' },
	{ id: '220', country_code: 'TO', value: 'Tonga' },
	{ id: '221', country_code: 'TT', value: 'Trinidad and Tobago' },
	{ id: '222', country_code: 'TN', value: 'Tunisia' },
	{ id: '223', country_code: 'TR', value: 'Turkey' },
	{ id: '224', country_code: 'TM', value: 'Turkmenistan' },
	{ id: '225', country_code: 'TC', value: 'Turks and Caicos Islands' },
	{ id: '226', country_code: 'TV', value: 'Tuvalu' },
	{ id: '227', country_code: 'UG', value: 'Uganda' },
	{ id: '228', country_code: 'UA', value: 'Ukraine' },
	{ id: '229', country_code: 'AE', value: 'United Arab Emirates' },
	{ id: '230', country_code: 'GB', value: 'United Kingdom' },
	{ id: '231', country_code: 'US', value: 'United States' },
	{ id: '232', country_code: 'UM', value: 'United States minor outlying islands' },
	{ id: '233', country_code: 'UY', value: 'Uruguay' },
	{ id: '234', country_code: 'UZ', value: 'Uzbekistan' },
	{ id: '235', country_code: 'VU', value: 'Vanuatu' },
	{ id: '236', country_code: 'VA', value: 'Vatican City State' },
	{ id: '237', country_code: 'VE', value: 'Venezuela' },
	{ id: '238', country_code: 'VN', value: 'Vietnam' },
	{ id: '239', country_code: 'VG', value: 'Virgin Islands (British)' },
	{ id: '240', country_code: 'VI', value: 'Virgin Islands (U.S.)' },
	{ id: '241', country_code: 'WF', value: 'Wallis and Futuna Islands' },
	{ id: '242', country_code: 'EH', value: 'Western Sahara' },
	{ id: '243', country_code: 'YE', value: 'Yemen' },
	{ id: '244', country_code: 'ZR', value: 'Zaire' },
	{ id: '245', country_code: 'ZM', value: 'Zambia' },
	{ id: '246', country_code: 'ZW', value: 'Zimbabwe' },
];
export default workingcountries;
